version: "3.8"

services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/src/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "
      while ! nc -z postgres 5432; do
      echo 'Waiting for PostgreSQL to start...';
      sleep 1;
      done;
      npx prisma generate &&
      npx prisma migrate deploy &&
      npx prisma db push &&
      npm run dev
      "

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
